# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  rubocop:
    docker:
      - image: circleci/ruby:3.1.3
    steps:
      - checkout
      # - run:
      #     name: Install dependencias
      #     command: gem install bundler
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Run Rubocop
          command: rubocop
  rspec:
    docker:
      - image: circleci/ruby:3.1.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: gem install bundler
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Run RSpec
          command: rspec

          

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  version: 2
  build:
    jobs:
      - rubocop
      - rspec
